baseURL: "https://example.com"
languageCode: "pt-br"
title: "Duodraco"
pygmentsstyle: 'monokai'

# Theme settings
theme: massively
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
